all:
	go build -o build/mpr -ldflags "-X main.Version=$$(git describe --tags)" ./...

cross:
	GOOS=darwin GOARCH=amd64 go build -o build/mpr-darwin-amd64 ./...
	GOOS=darwin GOARCH=arm64 go build -o build/mpr-darwin-arm64 ./...
	GOOS=linux GOARCH=amd64 go build -o build/mpr-linux-amd64 ./...
	GOOS=linux GOARCH=arm64 go build -o build/mpr-linux-arm64 ./...
	GOOS=windows GOARCH=amd64 go build -o build/mpr-windows-amd64.exe ./...
	GOOS=windows GOARCH=arm64 go build -o build/mpr-windows-arm64.exe ./...
	for f in build/*; do \
		gzip -f $$f; \
	done

fmt:
	go fmt ./...

test:
	go test ./...

clean:
	rm -rf build/
